最小値・最大値

In [1]:
# coding:utf-8
import numpy as np
import tensorflow as tf

# 4x4行列 要素の値は0〜100の乱数
data_a = np.random.randint(0, 100, (4,4))
const_a = tf.constant(data_a, dtype=tf.float32)

# 最小値 各行の最小値
argmin_op = tf.argmin(const_a, 1)
# 最大値 各行の最大値
argmax_op = tf.argmax(const_a, 1)

with tf.Session() as sess:
    c, min, max = sess.run([const_a,argmin_op,argmax_op])
    print c
    print min
    print max

[[ 61.  83.  60.  26.]
 [ 11.   5.  26.  49.]
 [ 93.  80.  25.  99.]
 [ 89.  57.  60.  45.]]
[3 1 2 3]
[1 3 3 0]
