Clip

In [3]:
# coding:utf-8
import tensorflow as tf

sess = tf.Session()
p = tf.constant([[0.0,0.25],[0.5,1.0]], dtype=tf.float32, shape=(2,2))
# 値を指定した範囲の中に収まるようにする
value = tf.clip_by_value(p, 1e-10, 1.0)

print p.eval(session=sess)
print value.eval(session=sess)

[[ 0.    0.25]
 [ 0.5   1.  ]]
[[  1.00000001e-10   2.50000000e-01]
 [  5.00000000e-01   1.00000000e+00]]


Clip、Sessionで囲う

In [4]:
# coding:utf-8
import tensorflow as tf

with tf.Session() as sess:
  p = tf.constant([[0.0,0.25],[0.5,1.0]], dtype=tf.float32, shape=(2,2))
  # 値を指定した範囲の中に収まるようにする
  value = tf.clip_by_value(p, 1e-10, 1.0)

  print p.eval()
  print value.eval()

[[ 0.    0.25]
 [ 0.5   1.  ]]
[[  1.00000001e-10   2.50000000e-01]
 [  5.00000000e-01   1.00000000e+00]]
