和

In [1]:
import tensorflow as tf 
import numpy as np

# 2 x 2行列のPlaceholder
x = tf.placeholder(tf.float32, shape=(2,2))
y = tf.placeholder(tf.float32, shape=(2,2))

# [[1,2],
#  [3,4]]
mat_a = np.arange(1,5).reshape(2,2)
# [[11, 12],
#  [13,14]]
mat_b = np.arange(11,15).reshape(2,2)

# 和のオペレーション
add_op = tf.add(x, y)

# セッション
sess = tf.Session()

# 実行
result_mat = sess.run(add_op, feed_dict={x:mat_a, y:mat_b})

# 結果を表示
print result_mat

[[ 12.  14.]
 [ 16.  18.]]


差

In [6]:
# 差のオペレーション
sub_op = tf.subtract(x, y)

# 実行
result_mat = sess.run(sub_op, feed_dict={x:mat_a, y:mat_b})

# 結果を表示
print result_mat

[[-10. -10.]
 [-10. -10.]]


積

In [8]:
# 積のオペレーション
matmul_op = tf.matmul(x, y)

# 実行
result_mat = sess.run(matmul_op, feed_dict={x:mat_a, y:mat_b})

# 結果を表示
print result_mat

[[ 37.  40.]
 [ 85.  92.]]


要素の積

In [11]:
# 積のオペレーション
mul_op = tf.multiply(x, y)

# 実行
result_mat = sess.run(mul_op, feed_dict={x:mat_a, y:mat_b})

# 結果を表示
print result_mat

[[ 11.  24.]
 [ 39.  56.]]
