Sessionの保存と読み込み

In [9]:
import numpy as np
import tensorflow as tf

# 3x3行列の乱数生成オペレーション
rand_op = tf.random_normal(shape=(3,3))
# 3x3行列のVariable このノードが保存される
x = tf.Variable(tf.zeros(shape=(3,3)))
# xに3x3の乱数行列を割り当てるオペレーション
update_x = tf.assign(x, rand_op)

# セッションの保存・読み込みを行うオブジェクト
saver = tf.train.Saver()

# 保存用のセッション
# rand_opの実行ごとにxノードには違う乱数が格納される
# そのときのセッションが保存される
with tf.Session() as sess1:
  sess1.run(tf.global_variables_initializer())
  for i in range(0, 3):
    # rand_opを実行して、3x3行列を生成し、xに割り当てる
    sess1.run(update_x)
    # xの値を表示する
    print "--save ./rand-%d--" % i
    print sess1.run(x)
    # セッション情報を保存する
    saver.save(sess1, "./rand", global_step=i)

# セッションの読み込み
with tf.Session() as sess2:
  sess2.run(tf.global_variables_initializer())
  # 最後のセッションを読み込む
  saver.restore(sess2, "./rand-2")
  print "--load ./rand-2--"
  print sess2.run(x)

--save ./rand-0--
[[ 0.56738025  1.29318893  0.20012558]
 [ 0.05409123  0.5954473   0.94214749]
 [ 1.36393642  0.00922111  0.01840344]]
--save ./rand-1--
[[ 0.00793184  0.28140947 -0.09582984]
 [ 2.01118255 -0.24437483 -1.63220096]
 [ 0.03120653  1.01750195 -0.23053376]]
--save ./rand-2--
[[ 1.99330962  0.59653908 -1.28212738]
 [-0.37193841 -0.44014138 -0.58220094]
 [ 0.17938922  0.49688783 -0.74690545]]
--load ./rand-2--
[[ 1.99330962  0.59653908 -1.28212738]
 [-0.37193841 -0.44014138 -0.58220094]
 [ 0.17938922  0.49688783 -0.74690545]]
