Tensorの型・次元数・ランク・サイズ

In [1]:
# coding:utf-8
import numpy as np
import tensorflow as tf

# 標準正規分布による乱数を持つ3x3行列
x_data = np.random.randn(3, 3)
# 3x3のTensor
x = tf.constant(x_data, shape=(3,3))

sess = tf.Session()

# 実行結果
print "--run--"
print sess.run(x)
# 型
print "--dtype--"
print x.dtype
# 次元数
print "--shape---"
print sess.run(tf.shape(x))
# ランク
print "--rank--"
print sess.run(tf.rank(x))
# サイズ
print "--size--"
print sess.run(tf.size(x))

--run--
[[-1.30151387 -0.27209197 -0.02436113]
 [-0.11732982 -0.3129898  -0.67891681]
 [ 0.4651189   0.27368295  1.52785832]]
--dtype--
<dtype: 'float64'>
--shape---
[3 3]
--rank--
2
--size--
9
