# Tensorの型・次元数・ランク・サイズ
---

In [1]:
# coding:utf-8
import numpy as np
import tensorflow as tf

In [2]:
# 標準正規分布による乱数を持つ3*3行列
x_data = np.random.randn(3,3)
# 3*3のTensor
x = tf.constant(x_data,shape=(3,3))

sess = tf.Session()

In [3]:
#実行結果
print "--run--"
print sess.run(x)

--run--
[[ 0.31792868 -1.41731464 -1.68438509]
 [-0.11950915 -0.66478869  0.07233121]
 [-0.49994878  0.07171369  0.91297385]]


In [4]:
# 型
print x.dtype

<dtype: 'float64'>


In [8]:
# 次元数
print sess.run(tf.shape(x))

[3 3]


In [9]:
# ランク
print sess.run(tf.rank(x))

2


In [10]:
# サイズ
print sess.run(tf.size(x))

9


## 参考

* https://www.tensorflow.org/versions/r1.0/resources/dims_types.html