# セッションの保存・読み込み
---
セッション内の`Variables`を保存・読み込む。モデルの学習時にパラメタの値を保存しておきたい場合に利用する。

## Sample

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
# 3x3行列の乱数生成オペレーション
rand_op = tf.random_normal(shape=(3,3))
# 3x3行列のVariable このノードが保存される
x = tf.Variable(tf.zeros(shape=(3,3)))
# xに3x3の乱数行列を割り当てるオペレーション
update_x = tf.assign(x, rand_op)

In [3]:
# セッションの保存・読み込みを行うオブジェクト
saver = tf.train.Saver()

In [5]:
# 保存用のセッション
# rand_opの実行ごとにxノードには違う乱数が格納される
# その時のセッションが保存される
with tf.Session() as sess1:
  sess1.run(tf.global_variables_initializer())
  for i in range(0,3):
    # rand_opを実行して、3x3行列を生成し、xに割り当てる
    sess1.run(update_x)
    # xの値を表示する
    print "--save ./ckpt/rand-%d" % i
    print sess1.run(x)
    # セッション情報を保存する
    saver.save(sess1,"./ckpt/rand", global_step=i)

--save ./ckpt/rand-0
[[ 0.41520497  1.30850315  0.79608464]
 [-1.05371237  0.4179754   1.70405078]
 [-2.09356713  1.65813887  2.04488707]]
--save ./ckpt/rand-1
[[ 0.43886122 -0.48472795 -2.66985703]
 [ 0.34088948  0.78776151 -1.56999636]
 [-1.7500118  -0.51133436 -1.34959686]]
--save ./ckpt/rand-2
[[ 1.59489274  0.13907592  1.54993415]
 [-1.54051971  0.44665596 -0.01095306]
 [-0.80483067 -1.47003615  0.5624854 ]]


In [6]:
# セッションの読み込み
with tf.Session() as sess2:
  sess2.run(tf.global_variables_initializer())
  # 最後のセッションを読み込む
  saver.restore(sess2, "./ckpt/rand-2")
  print "--load ./ckpt/rand-2"
  print sess2.run(x)

INFO:tensorflow:Restoring parameters from ./ckpt/rand-2
--load ./ckpt/rand-2
[[ 1.59489274  0.13907592  1.54993415]
 [-1.54051971  0.44665596 -0.01095306]
 [-0.80483067 -1.47003615  0.5624854 ]]


以下のようなファイルが生成させる

```shell
$ ls ./ckpt/rand*
rand-0.data-00000-of-00001 rand-1.data-00000-of-00001 rand-2.data-00000-of-00001
rand-0.index               rand-1.index               rand-2.index
rand-0.meta                rand-1.meta                rand-2.meta
```

## ノート

セッションの読み込み時にファイルパスを"ファイル名"とすると失敗する可能性あり。"./ファイル名"としたところ成功した。

実行環境:

* Python 2.7.12 :: Anaconda 4.1.1 (x86_64)
* TensorFlow 0.12.0-rc0

類似の不具合:

* https://github.com/tensorflow/tensorflow/issues/571

---

## Notebook

[https://github.com/FaBoPlatform/TensorFlow/blob/master/notebooks/session.ipynb](https://github.com/FaBoPlatform/TensorFlow/blob/master/notebooks/session.ipynb)