# 標準正規分布のTensorを作る
---
正規分布により乱数を生成する。

> tf.random_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)


|変数|概要|
|:--|:--|
|shape|Tensorのサイズ|
|mean|平均|
|stdev|標準偏差| 
|dtype|値の型|
|seed|シード|
|name|操作名|

デフォルトでは`mean=0.0, stddev=1.0`となっており、標準正規分布になっている。

## Sample

正規分布

In [3]:
# coding:utf-8
import tensorflow as tf
import numpy as np

In [4]:
# 標準正規分布による乱数を値にもつ3x3行列
x = tf.random_normal(shape=(3,3))

sess = tf.Session()
y = sess.run(x)
print y
sess.close()

[[  2.14010453e+00   1.63878024e-01  -8.76375496e-01]
 [ -3.26650083e-01   6.48519516e-01   3.05447489e-01]
 [ -7.65992641e-01  -4.91622428e-04  -4.55635995e-01]]


1万件に増やし、正規分布が1.0に近づくかを確認　

In [6]:
# 標準正規分布による乱数を値にもつ3x3行列
x = tf.random_normal(shape=(5000,2))

sess = tf.Session()
y = sess.run(x)

print np.average(y)
print np.std(y)
sess.close()

0.00350512
1.00401


stddevに10指定し、平均値が10に近づく事を確認

In [7]:
# 標準正規分布による乱数を値にもつ3x3行列
x = tf.random_normal(shape=(5000,2), mean=1,stddev=10)

sess = tf.Session()
y = sess.run(x)

print np.average(y)
print np.std(y)
sess.close()

1.09163
10.0327


## 参考

* https://www.tensorflow.org/api_docs/python/tf/random_normal

# 切断正規分布
---
標準偏差の2倍の間に収まるような乱数を生成する

> tf.truncated_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)

|変数|概要|
|:--|:--|
|shape|Tensorの形式|
|mean|正規分布の平均。デフォルト 0.0|
|stdev|正規分布の標準偏差。デフォルト 1.0| 
|dtype|値の型|

## Sample

切断正規分布

In [8]:
# デフォルトは1.0なので、乱数の値は-2~2の間に収まる
truncated_normal = tf.truncated_normal([20])
sess = tf.Session()
val = sess.run(truncated_normal)

print(val)
sess.close()

[-0.30878934  0.35897934 -0.88472492  0.89773321 -1.82789302  1.24759364
 -1.60505593  1.10819244  1.16885257  0.05746071  1.51047444  1.92377067
  1.10624337  1.09388161 -0.0676482   0.17268701  1.5651418   0.02382554
  0.55061102  0.12201686]


## 参考

* [切断正規分布の解説](https://ja.wikipedia.org/wiki/%E5%88%87%E6%96%AD%E6%AD%A3%E8%A6%8F%E5%88%86%E5%B8%83)

# 乱数のシード
---
学習結果および計算結果に再現性を持たせるために使う。

> tf.set_random_seed(seed)

|変数|概要|
|:--|:--|
|seed|Seed値|


In [9]:
# 乱数のシードを設定する
tf.set_random_seed(20200724)

# 標準正規分布による乱数の値を持つ4x4行列
x = tf.random_normal(shape=(4,4))

sess = tf.Session()
y = sess.run(x)
print y

[[ 0.58003223 -1.78534365 -0.07899306  0.09836151]
 [-0.21497221 -0.76032352  1.3579433   0.60065633]
 [-0.2302579   1.11828232 -0.44764459 -0.99638569]
 [ 0.45086274  1.80219543 -0.99858069  0.50142682]]


## 参考

* https://www.tensorflow.org/api_docs/python/tf/set_random_seed