# 最小値・最大値
---
> tf.argmin(input, dimension, name=None)

最小値のインデックスを返す  

|引数名|概要|
|:--|:--|
|input|引数として渡すTensor|
|dimension|処理対象とする次元, ベクトルの場合は0、行列の場合、0:列、1:行|

> tf.argmax(input, dimension, name=None)

最大値のインデックスを返す

|引数名|概要|
|:--|:--|
|input|引数として渡すTensor|
|dimension|処理対象とする次元, ベクトルの場合は0、行列の場合、0:列、1:行|

In [1]:
# coding:utf-8
import numpy as np
import tensorflow as tf

In [2]:
# 4x4行列　要素の値は0~100の乱数
data_a = np.random.randint(0,100,(4,4))
const_a = tf.constant(data_a,dtype=tf.float32)

In [3]:
# 最小値　各行の最小値
argmin_op = tf.argmin(const_a,1)
# 最大値　各行の最大値
argmax_op = tf.argmax(const_a,1)

In [4]:
with tf.Session() as sess:
  c,min,max = sess.run([const_a,argmin_op,argmax_op])
  print c
  print min
  print max

[[ 88.  26.  38.  88.]
 [  1.  81.  88.  46.]
 [ 79.  48.   6.  10.]
 [ 77.  52.  24.  64.]]
[1 0 2 2]
[0 2 0 0]


## 参考

* https://www.tensorflow.org/api_docs/python/tf/argmin
* https://www.tensorflow.org/api_docs/python/tf/argmax