# Tensor(行列)の和
---
## tf.add

> tf.add(x, y, name=None)

|変数|概要|
|:--|:--|
|x|half, float32, float64, uint8, int8, int16, int32, int64, complex64, complex128, stringの型の値を引数で渡せる|
|y|half, float32, float64, uint8, int8, int16, int32, int64, complex64, complex128, stringの型の値を引数で渡せる|
|name|操作の名前(任意)|

# Sample
> mat1 + mat2 = result_mat

$
\begin{bmatrix}
1 & 2 \\
3 & 4 
\end{bmatrix}
$ + 
$
\begin{bmatrix}
11 & 12 \\
13 & 14 
\end{bmatrix}
$=
$
\begin{bmatrix}
12 & 14 \\
16 & 18 
\end{bmatrix}
$

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# 2x2行列のPlaceholder
x = tf.placeholder(dtype=tf.float32,shape=(2,2))
y = tf.placeholder(dtype=tf.float32,shape=(2,2))

In [3]:
# [[1,2],
#  [3,4]]
mat_a = np.arange(1,5).reshape(2,2)
mat_a

array([[1, 2],
       [3, 4]])

In [4]:
# [[11,12],
#  [13,14]]
mat_b = np.arange(11,15).reshape(2,2)
mat_b

array([[11, 12],
       [13, 14]])

In [5]:
# 和のオペレーション
add_op = tf.add(x,y)

In [7]:
# セッション
sess = tf.Session()

# 実行
result_mat = sess.run(add_op,feed_dict={x:mat_a,y:mat_b})

# 結果を表示
print(result_mat)

[[ 12.  14.]
 [ 16.  18.]]


## 参考

https://www.tensorflow.org/api_docs/python/tf/add




# Tensor(行列)の差
---
## tf.subtract

> tf.subtract(x, y, name=None)

|変数|概要|
|:--|:--|
|x|half, float32, float64, int32, int64, complex64, complex128の型の値を引数で渡せる|
|y|half, float32, float64, int32, int64, complex64, complex128の型の値を引数で渡せる|
|name|操作の名前(任意)|

## Sample

> mat2 - mat1 = result_mat  

$
\begin{bmatrix}
11 & 12 \\
13 & 14 
\end{bmatrix}
$ -
$
\begin{bmatrix}
1 & 2 \\
3 & 4 
\end{bmatrix}
$=
$
\begin{bmatrix}
10 & 10 \\
10 & 10 
\end{bmatrix}
$

In [10]:
# 差のオペレーション
sub_op = tf.subtract(x,y)

# 実行
result_mat = sess.run(sub_op,feed_dict={x:mat_b,y:mat_a})

# 結果を表示
print(result_mat)

[[ 10.  10.]
 [ 10.  10.]]


## 参考

https://www.tensorflow.org/api_docs/python/tf/subtract

# Tensor(行列)の積
---
## tf.matmul

> tf.matmul(x, y, name=None)

|変数|概要|
|:--|:--|
|x|half, float32, float64, uint8, int8, uint16, int16, int32, int64, complex64, complex128の型の値を引数で渡せる|
|y|half, float32, float64, uint8, int8, uint16, int16, int32, int64, complex64, complex128の型の値を引数で渡せる|
|name|操作の名前(任意)|

## Sample

> mat1 x mat2 = result_mat

$
\begin{bmatrix}
1 & 2 \\
3 & 4 
\end{bmatrix}
$ x 
$
\begin{bmatrix}
11 & 12 \\
13 & 14 
\end{bmatrix}
$=
$
\begin{bmatrix}
37 & 40 \\
85 & 92 
\end{bmatrix}
$

In [12]:
# 積のオペレーション
matmul_op = tf.matmul(x,y)

# 実行
result_mat = sess.run(matmul_op,feed_dict={x:mat_a,y:mat_b})

# 結果を表示
print result_mat

[[ 37.  40.]
 [ 85.  92.]]


## 参考

https://www.tensorflow.org/api_docs/python/tf/matmul

# Tensor(行列)の要素の積
---
## tf.multiply

> tf.multiply(mat_a, mat_b, name=None)

|変数|概要|
|:--|:--|
|x|half, float32, float64, uint8, int8, uint16, int16, int32, int64, complex64, complex128の型の値を引数で渡せる|
|y|half, float32, float64, uint8, int8, uint16, int16, int32, int64, complex64, complex128の型の値を引数で渡せる|
|name|操作の名前(任意)|

## Sample

> mat_a x mat_b = result_mat

$
\begin{bmatrix}
1 & 2 \\
3 & 4 
\end{bmatrix}
$ *
$
\begin{bmatrix}
11 & 12 \\
13 & 14 
\end{bmatrix}
$=
$
\begin{bmatrix}
11 & 24 \\
39 & 56 
\end{bmatrix}
$

このような積をアダマール積という　

In [13]:
# 積のオペレーション
mul_op = tf.multiply(x,y)

# 実行
result_mul = sess.run(mul_op,feed_dict={x:mat_a,y:mat_b})

# 結果を表示
print(result_mul)

[[ 11.  24.]
 [ 39.  56.]]


## 参考

https://www.tensorflow.org/api_docs/python/tf/multiply

* アダマール積について
https://ja.wikipedia.org/wiki/%E3%82%A2%E3%83%80%E3%83%9E%E3%83%BC%E3%83%AB%E7%A9%8D