# 標準正規分布のTensorを作る
---
正規分布により乱数を生成する。

> tf.random_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)


|変数|概要|
|:--|:--|
|shape|Tensorのサイズ|
|mean|平均|
|stdev|標準偏差| 
|dtype|値の型|
|seed|シード|
|name|操作名|

デフォルトでは`mean=0.0, stddev=1.0`となっており、標準正規分布になっている。

## Sample

正規分布

In [3]:
# coding:utf-8
import tensorflow as tf
import numpy as np

In [4]:
# 標準正規分布による乱数を値にもつ3x3行列
x = tf.random_normal(shape=(3,3))

sess = tf.Session()
y = sess.run(x)
print y
sess.close()

[[  2.14010453e+00   1.63878024e-01  -8.76375496e-01]
 [ -3.26650083e-01   6.48519516e-01   3.05447489e-01]
 [ -7.65992641e-01  -4.91622428e-04  -4.55635995e-01]]


1万件に増やし、正規分布が1.0に近づくかを確認　

In [6]:
# 標準正規分布による乱数を値にもつ3x3行列
x = tf.random_normal(shape=(5000,2))

sess = tf.Session()
y = sess.run(x)

print np.average(y)
print np.std(y)
sess.close()

0.00350512
1.00401


stddevに10指定し、平均値が10に近づく事を確認

In [7]:
# 標準正規分布による乱数を値にもつ3x3行列
x = tf.random_normal(shape=(5000,2), mean=1,stddev=10)

sess = tf.Session()
y = sess.run(x)

print np.average(y)
print np.std(y)
sess.close()

1.09163
10.0327


## 参考

* [切断正規分布の解説](https://ja.wikipedia.org/wiki/%E5%88%87%E6%96%AD%E6%AD%A3%E8%A6%8F%E5%88%86%E5%B8%83)
* https://www.tensorflow.org/api_docs/python/tf/random_normal