# ソート
---

In [4]:
# coding:utf-8
import numpy as np

# 範囲0〜100の乱数を持つ1次元配列
x = np.random.randint(0, 100, 10)
# 範囲0〜100の乱数を持つ4x4行列
y = np.random.randint(0, 100, (4,4))

print x

[12 19 53 66 26  2 22 49 48 15]


In [5]:
# 昇順に整列する
# 注意: np.sort()は破壊的操作
x.sort()
print x

[ 2 12 15 19 22 26 48 49 53 66]


In [6]:
print y

[[ 5 63 62 90]
 [98 20 63 12]
 [37 49 62 66]
 [39 42 32 45]]


In [7]:
# yをコピーする
y1 = np.array(y)
y2 = np.array(y)
# 列単位で昇順に整列する
y1.sort(0)
print y1

[[ 5 20 32 12]
 [37 42 62 45]
 [39 49 62 66]
 [98 63 63 90]]


In [8]:
# 行単位で昇順に整列する
# 引数がない場合は、デフォルト
y2.sort(1)
print y2

[[ 5 62 63 90]
 [12 20 63 98]
 [37 49 62 66]
 [32 39 42 45]]
