# 平均・分散・標準偏差
---

In [1]:
# coding:utf-8
import numpy as np

# 3x3行列
x = np.arange(9).reshape(3,3)
print x

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [2]:
# 平均
print x.mean()

4.0


In [3]:
# 分散
print x.var()

6.66666666667


In [4]:
# 標準偏差
print x.std()

2.58198889747


In [5]:
# 列単位での平均・分散・標準偏差
print x.mean(0)
print x.var(0)
print x.std(0)

[ 3.  4.  5.]
[ 6.  6.  6.]
[ 2.44948974  2.44948974  2.44948974]


In [6]:
# 行単位での平均・分散・標準偏差
print x.mean(1)
print x.var(1)
print x.std(1)

[ 1.  4.  7.]
[ 0.66666667  0.66666667  0.66666667]
[ 0.81649658  0.81649658  0.81649658]
