# さまざまな分布に従う乱数

|関数名|説明|
|:-:|:-:|
|`np.random.binomial(n,p,size)`|二項分布|
|`np.random.normal(loc,scale,size)`|正規分布|
|`np.random.beta(a,b,size)`|ベータ分布|
|`np.random.chisquare(df,size)`|カイ二乗分布|
|`np.random.gamma(shape,scale,size)`|ガンマ関数|
|`np.random.uniform(low,high,size)`|区間0<=x<1の一様分布|

In [5]:
# coding:utf-8
import numpy as np

# 二項分布に従う乱数
binomial = np.random.binomial(10, 0.5, (2,2))
print binomial

[[7 0]
 [7 6]]


In [6]:
# 正規分布に従う乱数
normal = np.random.normal(0, 1, (2,2))
print normal

[[-2.01677692 -0.12600801]
 [-0.359088   -1.50765792]]


In [7]:
# ベータ分布に従う乱数
beta = np.random.beta(1, 1, (2,2))
print beta

[[ 0.63237931  0.08976079]
 [ 0.26943176  0.07292672]]


In [8]:
# カイ二乗分布に従う乱数
chisquare = np.random.chisquare(1, (2,2))
print chisquare

[[ 0.36477184  0.15991732]
 [ 1.86645181  0.70713959]]


In [9]:
# ガンマ分布
gamma = np.random.gamma(2, 1, (2,2))
print gamma

[[ 1.86792088  2.43415547]
 [ 1.15937232  0.52924301]]


In [10]:
# [0,1)の一様分布
uniform = np.random.uniform(0, 1, (2,2))
print uniform

[[ 0.49393402  0.20058058]
 [ 0.69737889  0.230199  ]]
