# 行列の演算
---
<div style="text-align:center;"><h2>Sample</h2></div>

|演算|説明|
|:-:|:-:|
|+|行列の和|
|-|行列の差|
|np.dot(a, b) または a.dot(b)|行列の積|
|*|行列の**要素**同士の積|
|/|行列の**要素**同士の商|

In [2]:
# coding:utf-8
import numpy as np

# 2x2行列a
a = np.array([[2.0, 1.0], [4.0, 2.0]])
a

array([[ 2.,  1.],
       [ 4.,  2.]])

In [3]:
# 2x2行列b
b = np.array([[1.0, 1.0], [6.0, 3.0]])
b

array([[ 1.,  1.],
       [ 6.,  3.]])

In [4]:
# 行列の和
print a + b

[[  3.   2.]
 [ 10.   5.]]


In [5]:
# 行列の差
print a - b

[[ 1.  0.]
 [-2. -1.]]


In [6]:
# 行列の積
print np.dot(a, b)

[[  8.   5.]
 [ 16.  10.]]


In [7]:
# 以下も同様
print a.dot(b)

[[  8.   5.]
 [ 16.  10.]]


In [8]:
# 行列の要素同士の積
print a * b

[[  2.   1.]
 [ 24.   6.]]


In [9]:
# 行列の要素同士の商
print a / b

[[ 2.          1.        ]
 [ 0.66666667  0.66666667]]
