# 行列関数
---

<div style="text-align:center;">行列の計算を行う数学関数のサンプル</div>

|関数名|説明|
|:-:|:-:|
|`np.linalg.norm(x)`|ノルム|
|`np.diag(x)`|ベクトルを対角行列にする|
|`np.linalg.det(x)`|行列式|
|`np.linalg.inv(x)`|逆行列|
|`np.dot(x)`|行列の内積|
|`np.trace(x)`|対角和|
|`np.linalg.eig(x)`|固有行列|
|`np.eye(x)`|単位行列|
|`np.linalg.solve(x, y)`|連立方程式の解|

In [2]:
# coding:utf-8
import numpy as np

# [ 1.  2.  3.]
x = np.arange(1.0, 4.0)
print x

[ 1.  2.  3.]


In [3]:
# ベクトルのノルム(距離)
print np.linalg.norm(x)

3.74165738677


In [4]:
# ベクトルを対角行列にする
diag_x = np.diag(x)
diag_x

array([[ 1.,  0.,  0.],
       [ 0.,  2.,  0.],
       [ 0.,  0.,  3.]])

In [5]:
# 行列式
print np.linalg.det(diag_x)

6.0


In [6]:
# 逆行列
print np.linalg.inv(diag_x)

[[ 1.          0.          0.        ]
 [ 0.          0.5         0.        ]
 [ 0.          0.          0.33333333]]


In [10]:
# 3x3単位行列
e = np.eye(3)
print(e)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [11]:
# 行列の内積
print np.dot(diag_x, e)

[[ 1.  0.  0.]
 [ 0.  2.  0.]
 [ 0.  0.  3.]]


In [12]:
# 対角和
print np.trace(diag_x)

6.0


In [13]:
# 固有値、固有ベクトル
print np.linalg.eig(diag_x)

(array([ 1.,  2.,  3.]), array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]]))


In [14]:
# 連立方程式の解
# 2x+y+z = 15
# 4x+6y+3z = 41
# 8x+8y+9z = 83
# 解 : x=5,y=2,z=3
# 薩摩順吉, 四ツ谷晶二, "キーポイント線形代数" p.2より
a = np.array([[2,1,1],[4,6,3],[8,8,9]])
b = np.array([[15],[41],[83]])
print np.linalg.solve(a, b)

[[ 5.]
 [ 2.]
 [ 3.]]
