# 結合関数
---

In [1]:
# coding:utf-8
import numpy as np

# 3x3行列
x = np.arange(0, 9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [2]:
# 3x3行列
y = np.random.randint(0, 10, (3,3))
y

array([[8, 4, 3],
       [0, 2, 7],
       [3, 4, 0]])

In [3]:
# 行列の結合
# 行方向に行列を結合する(デフォルト)
print np.concatenate((x,y), axis=0)

[[0 1 2]
 [3 4 5]
 [6 7 8]
 [8 4 3]
 [0 2 7]
 [3 4 0]]


In [8]:
# 以下も同様
print np.vstack((x,y))

[[0 1 2]
 [3 4 5]
 [6 7 8]
 [8 4 3]
 [0 2 7]
 [3 4 0]]


In [9]:
# 列方向に行列を結合する
print np.concatenate((x,y), axis=1)

[[0 1 2 8 4 3]
 [3 4 5 0 2 7]
 [6 7 8 3 4 0]]


In [6]:
# 以下も同様
print np.hstack((x,y))

[[0 1 2 8 4 3]
 [3 4 5 0 2 7]
 [6 7 8 3 4 0]]


In [7]:
# 同じ行と列の要素を並べる
print np.dstack((x,y))

[[[0 8]
  [1 4]
  [2 3]]

 [[3 0]
  [4 2]
  [5 7]]

 [[6 3]
  [7 4]
  [8 0]]]


In [10]:
# 3x3行列を、1列目、2列目で分割する
x1, x2, x3 = np.split(x,(1,2))
print x1
print x2
print x3

[[0 1 2]]
[[3 4 5]]
[[6 7 8]]
