# numpyオブジェクトの型・次元数・サイズ
---

In [2]:
# coding:utf-8
import numpy as np

# 正規分布に従った乱数が入っている3x3行列
x = np.random.randn(3, 3)
print x

[[ 0.89263043  1.30422366  2.17564018]
 [-2.50433914 -0.20731496  0.0921945 ]
 [-0.98971334 -0.41873715 -0.27814413]]


In [5]:
# 型
print x.dtype

float64


In [6]:
# 次元数
print x.shape

(3, 3)


In [7]:
# サイズ
print x.size

9


In [8]:
# 2x2x2多次元配列
y = np.arange(8).reshape(2,2,2)
print y

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [9]:
# 型
print y.dtype

int64


In [10]:
# 次元数
print y.shape

(2, 2, 2)


In [11]:
# サイズ
print y.size

8
